project_id = "jqirupugxgsqgydxaebt"

[functions.species-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.google-maps-proxy]
verify_jwt = false

[functions.google-earth-engine]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false

[functions.nearby-wildlife]
verify_jwt = false
